name: Deploy to VPS
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3 # Sabit sürüm
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            echo "Connecting to VPS..."
            whoami
            cd ~/projects/BeyrahaCurrent
            git pull origin main
            npm install
            npx nuxi build
            pm2 restart nuxt-app
            echo "Deployment completed"
